[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

# Serverless function config
[[functions]]
  name = "api"
  node_bundler = "esbuild"
  memory = 3008
  timeout = 60

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
